### ISSUE TITLE
Can't get example working

### ISSUE THREAD

**Issue by ScubaDaniel** [valendres/playwright-msw#15]
I'm using Storybook to host React components and navigating to [Storybook for Playwright testing](https://storybook.js.org/docs/react/writing-tests/importing-stories-in-tests#example-with-playwright). I have [MSW working with Storybook](https://github.com/mswjs/examples/tree/master/examples/with-storybook) fine, but want the ability to define handlers in Playwright tests rather than making new stories for each request use-case. 

I disable MSW from starting in the browser just fine when running tests from Playwright, so I know it's not an issue with that. I can't get this library to intercept requests though.

I've used the example and added the fixture as directed and even tried setting up the server after navigating to the Storybook page, but I can't get any of my handlers to intercept a request. Are there any troubleshooting steps you could provide?

Versions:
@playwright/test: ^1.22.2
@storybook/react: ^6.4.19
msw: ^0.47.3
playwright-msw: ^1.0.0

Routes:
Navigating to page: http://localhost:6007/iframe.html?args=&id=someid
Posting to route: "/common/someroute"
* Request URL: http://localhost:6007/common/debugmode
* Referrer Policy: strict-origin-when-cross-origin

**Comment by ScubaDaniel** [comment]
This sort of work-around seems to work: https://github.com/mswjs/msw/discussions/1322

It's interesting that MSW themselves use `page.evaluate` rather than the routing like you use.

**Comment by valendres** [comment]
Hey @ScubaDaniel, my apologies for the delay on responding to you. 

Unfortunately, I don't have any experience using Playwright with Storybook. However, I suspect this issue may be related to a breaking change in `msw@0.47.1`. As mentioned by @Azurewarth0920 in https://github.com/valendres/playwright-msw/issues/16, the callback for handling the mocked request was renamed from `onMockedResponseSent` to `onMockedResponse`. This unfortunately caused `playwright-msw` to be incompatible. 

With some help from @Azurewarth0920, we have upgraded `playwright-msw` to be compatible with the latest version of MSW. Would you be able to please try [playwright-msw@1.0.2](https://www.npmjs.com/package/playwright-msw/v/1.0.2) and let me know if this resolves the issue? If that doesn't work, I'd be happy to tinker with storybook integration and try to understand how to get this to work properly. 

> It's interesting that MSW themselves use page.evaluate rather than the routing like you use.

That is indeed interesting. I actually had no idea MSW was using playwright to test their library 😅

While it is possible to use `page.evaluate` to get a reference to the MSW instance and mock the requests via the browser, it likely assumes that you're running a dev server with MSW running in it. This means that the bundle & assets we're testing is not the same as the one that we're wanting to deploy to our users. Ideally, we should try to keep our testing environment as close to what the users are going to use. The routing method used by `playwright-msw` means that the API mocking is actually happening within the playwright layer, and not the browser itself. This allows the exact same bundle to be built, tested and deployed.

**Comment by valendres** [comment]
Leaving this issue open for now. @ScubaDaniel please feel free to close this issue if it has been resolved 🙂

**Comment by valendres** [comment]
Going to close this due to inactivity. Please feel free to re-open if this did not resolve the issue for you @ScubaDaniel.
