### ISSUE TITLE
The lib is broken as the msw upgraded to v0.47.1 or above.

### ISSUE THREAD

**Issue by Azurewarth0920** [valendres/playwright-msw#16]
Refs: https://github.com/mswjs/msw/blame/main/src/setupWorker/start/createFallbackRequestListener.ts#L49

The method name changed from `onMockedResponseSent` to `onMockedResponse`.

**Comment by valendres** [comment]
Thanks for raising this issue and creating a PR @Azurewarth0920. As mentioned in https://github.com/valendres/playwright-msw/pull/17#issuecomment-1267296039, I have recreated this PR as https://github.com/valendres/playwright-msw/pull/19 and merged it. 

This change has now been published as [playwright-msw@1.0.1](https://www.npmjs.com/package/playwright-msw/v/1.0.1).

Please let me know if this issue has not been resolved.
