### ISSUE TITLE
[Question] Can we enable credentials for mocked requests?

### ISSUE THREAD

**Issue by lesha1201** [valendres/playwright-msw#25]
Credentials are `omit` for MockedRequest. However, in WebKit browser there is an issue https://github.com/microsoft/playwright/issues/11937 with cookies aren't included for intercepted requests and because of that it doesn't work properly in case of WebKit. If credentials weren't omitted then `msw` could include them from its internal storage which fixes the issue with WebKit https://github.com/mswjs/cookies/blob/main/src/store.ts#L92. So can we remove `credentials: omit` or it's required for something else?

**Comment by valendres** [comment]
@lesha1201 Interesting, I wasn't aware of this issue. The good (or potentially bad, depending on how you look at it) is that I actually don't recall why I chose to omit credentials in the first place. Given that this doesn't cause the tests to fail within the repo, I'm happy for this to be removed. I'll make a change to do this and get it published shortly 🙂

**Comment by valendres** [comment]
Version 1.03 has been published with this change 🙂

https://github.com/valendres/playwright-msw/commit/26d3902ffe5601b39b58bd8f08cb1671783c5020

@lesha1201 Would you be able to help test that this resolves your issue and close this one if so?

**Comment by lesha1201** [comment]
@valendres It fixes my issue but I noticed that the store isn't cleared when running sequential tests so some test might affect another. In my case I can fix it by using `test.describe.parallel` but it's just a workaround.

**Comment by lesha1201** [comment]
I will create a PR to fix this.

**Comment by valendres** [comment]
@lesha1201 thanks for catching that and creating a PR to address it, it looks good so far.
https://github.com/valendres/playwright-msw/pull/30

Once we get some tests, it should be good to merge 🙂

**Comment by valendres** [comment]
[playwright-msw@1.0.4](https://www.npmjs.com/package/playwright-msw/v/1.0.4) has been published with the recent bugfix!

**Comment by valendres** [comment]
Closing this issue as this has now been resolved. Please feel free to re-open if necessary!
