### ISSUE TITLE
Target page, context or browser has been closed

### ISSUE THREAD

**Issue by lesha1201** [valendres/playwright-msw#26]
![image](https://user-images.githubusercontent.com/10157660/197556357-6051a003-c744-442d-af94-32da137b3647.png)

This error happens randomly. I guess it happens because of some promises aren't waited.

**Context:**
Node.js: v18.11.0
Playwright: v1.27.1
MSW: v0.47.4

**Comment by valendres** [comment]
Thanks for creating a PR to address this, I'll get this merged and published shortly 🙂

**Comment by valendres** [comment]
This change has been published in 1.0.3 🎉

Thanks again for your contribution!
