### ISSUE TITLE
Paths with query params aren't handled

### ISSUE THREAD

**Issue by lesha1201** [valendres/playwright-msw#38]
When we try to request some path with a query param, it can't find a matching handler since we use glob pattern.

For example, I have a handler for `/api/v1/documents/` and it handles it with `page.route('/api/v1/documents/', ...)`. Playwright uses glob pattern in that and in this case `/api/v1/documents/?foo=bar` won't pass.

[Example with glob patterns](https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2Fapi%2Fv1%2Fdocuments%2F&matches=false&tests=%2Fapi%2Fv1%2Fdocuments%2F&tests=%2Fapi%2Fv1%2Fdocuments%2F%3Ffoo%3Dbar)

**Comment by valendres** [comment]
Thanks for raising this @lesha1201. Taking a look at this now, I'll try to have a PR up shortly.

**Comment by valendres** [comment]
A fix for this issue has been published in [2.0.1](https://www.npmjs.com/package/playwright-msw). Please feel free to close this issue if resolved 🙂

**Comment by lesha1201** [comment]
@valendres There is one issue that I've noticed. Left a comment in PR https://github.com/valendres/playwright-msw/pull/40/files#r1020178001

**Comment by valendres** [comment]
Thanks @lesha1201. I've got a PR (https://github.com/valendres/playwright-msw/pull/41) up to address the outstanding issue. If you want to take a look at it and make sure it'll fix your bug, I'll merge and get this deployed ASAP.

**Comment by valendres** [comment]
Closing this issue as #40 and #41 have been merged. Please reopen this issue if it persists.
