### ISSUE TITLE
route.abort: Unknown error code: error

### ISSUE THREAD

**Issue by bel0v** [valendres/playwright-msw#54]
[thrown `error` code](https://github.com/valendres/playwright-msw/blob/3d08816b4175269e924620b086d464799aa9e46c/packages/playwright-msw/src/handler.ts#L65) is not accepted in playwright's [Route type](https://github.com/microsoft/playwright/blob/599ae30313a3c9f746905f73d18430c96e0eace4/docs/src/api/class-route.md#param-routeaborterrorcode)

They might have strictened the check somewhere in the code, I'm not sure. But anyway after I bumped all msw and playwright dependencies my test gives this error instead of internal one: `route.abort: Unknown error code: error`

As a solution perhaps the handler can just call `route.abort()`.

**Comment by valendres** [comment]
Thanks for the heads up and recommended solution @bel0v. I've created a PR: https://github.com/valendres/playwright-msw/pull/57

**Comment by valendres** [comment]
**Update:** after some further testing, I can confirm that `msw@0.49.3` did indeed introduce a compatibility issue. I've made an additional change to #57 that actually fixes the issue.

**Comment by valendres** [comment]
A fix for this has been released in [playwright-msw@2.2.0](https://www.npmjs.com/package/playwright-msw/v/2.2.0)

**Comment by bel0v** [comment]
thank you @valendres!
