### ISSUE TITLE
demo.spect.ts link not found

### ISSUE THREAD

**Issue by litan1106** [valendres/playwright-msw#62]
The final step is to use the extended test implementation within your playwright tests. e.g. within a [demo.spec.ts](https://github.com/valendres/playwright-msw/blob/main/packages/example/tests/playwright/specs/demo.spec.ts) file:

**Comment by valendres** [comment]
Sorry about this @litan1106. This file has been renamed to [rest.spec.ts](https://github.com/valendres/playwright-msw/blob/main/packages/example/tests/playwright/specs/rest.spec.ts). I have updated the README.md to reflect this.
