### ISSUE TITLE
Question: Does this library mock API calls?

### ISSUE THREAD

**Issue by JoshAwaze** [valendres/playwright-msw#82]
Hi, I'm trying to use v3 of this library in a sveltekit application and I can't seem to get any requests to be mocked. I've followed the guide by creating a mock worker fixture and using that test fixture within my tests. 

So I'm wondering does this library mock API calls or is just for page calls?

For added context I am using sveltekit and wish to mock external API calls that happen from the sveltekit server

**Comment by valendres** [comment]
Hey @JoshAwaze,

Thanks for reaching out with your question. Unfortunately, I haven't had the opportunity to work with SvelteKit yet, so my knowledge on its details is very limited.

Regarding the library, its primary function is to mock REST & GraphQL API calls that are executed at runtime in the browser. These are the calls you typically see in the network tab of Chrome's DevTools. It achieves this by mapping the MSWpaths to Playwright routes, allowing them to be intercepted using Playwright's [page.route](https://playwright.dev/docs/api/class-page#page-route) functionality. This mechanism effectively bridges the gap between the browser and the host environment orchestrating the tests.

From your description, it sounds like there might be server-side rendering (SSR) at play, which could imply that the API calls you're trying to mock aren't actually happening during the browser's runtime. If that's the case, `playwright-msw` might not be able to intercept these calls as it's designed for client-side interactions. 

To better understand the issue, could you confirm if these API calls are being made during SSR or client-side execution? This would help me understand the problem a bit better. Additionally, if it's feasible in your test environment, you might consider temporarily disabling SSR to see if that allows the API calls to occur client-side, where `playwright-msw` can intercept them. 

If you could share some more details or code snippets about how and when these API calls are made in your SvelteKit application, that would be really helpful for further troubleshooting.

**Comment by JoshAwaze** [comment]
Unfortunately I can't share code snippets of my application but hopefully I can get some time to create a minimal dummy application. 

The answer to your question about it being browser or SSR call is both aha although most are predominately called from `+page.server.ts`

https://kit.svelte.dev/docs/load

<img width="870" alt="Screenshot 2023-12-11 at 10 16 02" src="https://github.com/valendres/playwright-msw/assets/145982823/17c849e1-4039-4a09-a2be-7bd991e070d8">

```
// +page.ts
export const load = async () => {
 fetch(...)
}
```

**Comment by JoshAwaze** [comment]
With your answer about the primary objective of this library for being browser based network call mocking I can call this question confirmed and I'm willing to close this issue 👍
